### PR TITLE
fix some ui issues

### PR DESCRIPTION
**Pull request by zzcclp**
fix some ui issues

### CODE REVIEW

**Comment by frankleaf** [comment]
the UI issue had been fixed and don't need to change the ajax function and thank you

**Comment by frankleaf** [comment]
just put the  jaxbJsonProvider jar to the your spark lib that can work and don't need to init

**Comment by zzcclp** [comment]
> just put the jaxbJsonProvider jar to the your spark lib that can work and don't need to init

**Comment by zzcclp** [comment]
> just put the jaxbJsonProvider jar to the your spark lib that can work and don't need to init

which jars need to be put to spark libs? can you descript in doc?

**Pull request closed without merging**
